### ISSUE TITLE
Causes infinite loading screen glitch

### ISSUE THREAD

**Issue by adriesteia** [Evilvonbek/Lich-Fix-1.3-WIP#1]
Installing the mod causes the game to freeze on Build ID: 13207217
Refreshing the cache does not work

**Comment by Evilvonbek** [comment]
That would be because it's a mod updated to work with Game Version 1.3 and then no longer needed after that due to Owlcat Ruling on how the abilities worked and also bugfixes.

You are trying to use a mod that is almost two years old and multiple Game Versions never mind Build Versions out of date, so it is no surprise it is not working.

There is also no plan both by myself, since I no longer play the game and also have other demands on my time, or any other current WOTR Modders to update this mod since it was only needed to fix actual mechanical issues for a very short time.
![image](https://github.com/Evilvonbek/Lich-Fix-1.3-WIP/assets/58301486/afd3cd10-eb2b-47b8-8ecf-fd5354fa3f59)
